feat: add item requests
pparabol/java-shareit pull request #3
Opened 2023-07-19 12:00 UTC by pparabol

2023-07-19 17:58 UTC, EugeneLenkevich requested changes
Привет, Полина, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-07-19 17:58 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
>              "order by b.start desc")
order by b.start desc

В метод передается Pageable-объект, у него есть возможность задать сортировку, стоит ли сортировку задавать в запросе запросе, попробуй задать сортировку через этот объект :)

2023-07-19 17:58 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                bookings = bookingRepository.findByItemOwnerIdOrderByStartDesc(userId, pageRequest);
OrderByStartDesc

Опять таки сортировка :)

2023-07-19 17:58 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.getItems(userId, PageRequest.of(from / size, size));
Тут кстати можо не заморачиваться, а передавать как есть from и size. А там уже где то внутри сервиса создавать объект, не критично, но так же вроде как проще, что думаешь? :)

2023-07-19 17:58 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .requestId(item.getRequest() == null ? null : item.getRequest().getId())
Можно кстаи вот так записать.  Такой синтаксический сахар :)

Optional.ofNullable(item.getRequest())
.map(ItemRequest::getId)
.orElse(null)

2023-07-19 18:50 UTC, pparabol commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.getItems(userId, PageRequest.of(from / size, size));
Мне тоже кажется, что передавать from и size проще, но в теории был пример, где параметры запроса собирались в объект в контроллере, и дальше уже объект передавался, поэтому я тут так же сделала)

2023-07-19 19:02 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.getItems(userId, PageRequest.of(from / size, size));
Ну я и отметил что не критично)

2023-07-20 02:39 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-07-20 18:43 UTC, merged